# Generated by Django 3.1.3 on 2020-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='img')),
                ('state', models.CharField(max_length=64, verbose_name='状态')),
                ('parent', models.CharField(max_length=64, verbose_name='用户')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片表',
                'db_table': 'api_picture',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'api_user',
            },
        ),
    ]
