# Generated by Django 3.1.4 on 2020-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='base64',
            field=models.TextField(default=64, max_length=255, verbose_name='base64'),
            preserve_default=False,
        ),
    ]
