# Generated by Django 3.1.4 on 2020-12-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pic_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='base64',
        ),
    ]
