# Generated by Django 3.1.4 on 2020-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pic_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
    ]
