# Generated by Django 3.1.4 on 2020-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='time',
            field=models.CharField(max_length=64, verbose_name='时间'),
        ),
    ]
